import type { Metadata } from "next";
import localFont from 'next/font/local'
import { NavLinks } from '@/app/ui/Navlinks';

const myFont = localFont({
  src: '../../public/fonts/myfont.ttf',
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en">
      <div className={myFont.className}>
        <NavLinks />
        <main>
          {children}
        </main>
      </div>
    </div>
  );
}
